version: '3'
services:
  flask:
    build:
      context: .
      dockerfile: Dockerflask
    ports:
    - "5000:5000"
    volumes:
    - ..:/app
  postgres:
    image: postgres:9.3-alpine
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres